### ISSUE TITLE
关于泊松高斯和ELD模型的复现

### ISSUE THREAD

**Issue by frreason** [megvii-research/PMN#10]
####     您好，我尝试基于您开源的这一个代码去复现泊松高斯以及ELD的噪声模型，基于data_process里的Raw_Dataset指定noise_code(P, G, R Q)去实现噪声数据合成，训练还是基于trainer_SID.py，但是发现复现出来的结果跟您论文里的数据好像有一定的差距，我想请教一下我这个复现的方法有错误吗？

**Comment by fenghansen** [comment]
Q：“复现出来的结果跟您论文里的数据好像有一定的差距”
A：复现方式没错，但有±0.3dB左右的浮动比较正常。
1）论文里的数据用的是ELD官方模型转换过来的，和ELD论文是对齐的，不是我复现的。
2）我2020年复现的时候ELD还没有开源训练部分和参数，噪声生成部分是我复现补出来的，有差距很正常。尤其是SID数据集上，我当时标定没那么广只是按照ELD数据集的ISO范围标定的（大概ISO-400~ISO6400），延拓区间参数准确度不保证，所以只是在ELD数据集上和ELD大致对齐了。
3）clip参数需要全面检查对齐一下。零clip实际上不合理所以我们（含SFNR）在代码中有所变化，但ELD还是[0,1]两头裁剪。我代码改的时候没检查对ELD的兼容性。

**Comment by frreason** [comment]
很感谢您的回答，我尝试复现出来的结果在指定noise_code=PGRQ的时候，跟论文里的ELD方法在ELD数据集上的结果差了很多，在ratio=100的时候，PSNR差了有将近**3dB**，ratio=200的时候差了将近**4dB**，所以想请教一下您有没有基于data_process里的参数复现过ELD，或者是我复现的时候有哪一部分处理跟您是没有对齐的？
| 复现 | method | Ratio | PSNR | SSIM |
| :-: | :--: | :--: | :--: | :--: |
|  | ELD | 100 | 42.43 | 0.9069 |
|  |     | 200 | 39.08 | 0.8304 |

然后clip部分的处理我看了一下好像确实和ELD开源的代码处理有点区别，我重新尝试对齐看看会不会有改善。

**Comment by frreason** [comment]
您好，我尝试将0 clip对齐了ELD处理后，结果依旧没有改善，同时我将您的噪声合成代码(G+P+R+Q)迁移至ELD官方开源代码里替换了其noise_maker(G+P)，发现其存在一样的问题，与我上面贴的实验数据类似。
然后我看加噪部分您是在Kmin与Kmax区间随机采样，我对比了您代码里两个加噪函数，发现其Kmax差别较大：

```
cam_noisy_params['SonyA7S2_lowISO'] = {
        'Kmin':-1.67214, 'Kmax':0.42228, 'lam':-0.026, 'q':1/(2**14), 'wp':16383, 'bl':512,
        'sigRk':0.78782,  'sigRb':-0.34227,  'sigRsig':0.02832,
        'sigTLk':0.74043, 'sigTLb':0.86182, 'sigTLsig':0.00712,
        'sigGsk':0.82966, 'sigGsb':1.49343, 'sigGssig':0.00359,
        'sigReadk':0.82879, 'sigReadb':1.50601, 'sigReadsig':0.00362,
        'uReadk':0.01472, 'uReadb':0.01129, 'uReadsig':0.00034,
    }
```
```
    cam_noisy_params['SonyA7S2_highISO'] = {
        'Kmin':0.64567, 'Kmax':2.51606, 'lam':-0.025, 'q':1/(2**14), 'wp':16383, 'bl':512,
        'sigRk':0.62945,  'sigRb':-1.51040,  'sigRsig':0.02609,
        'sigTLk':0.74901, 'sigTLb':-0.12348, 'sigTLsig':0.00638,
        'sigGsk':0.82878, 'sigGsb':0.44162, 'sigGssig':0.00153,
        'sigReadk':0.82645, 'sigReadb':0.45061, 'sigReadsig':0.00156,
        'uReadk':0.00385, 'uReadb':0.00674, 'uReadsig':0.00039,
    }

```
```
    cam_noisy_params = {
        'SonyA7S2_16000': {'Kmax': 15.3008, 'lam': -0.060692135, 'sigGs': 17.833515, 'sigGssig': 0.19809262, 'sigTL': 8.877547, 'sigTLsig': 0.23338738, 'sigR': 1.5559287, 'sigRsig': 0.15791349, 'bias': 0, 'biassig': 0.09725099, 'q': 6.103515625e-05, 'wp': 16383, 'bl': 512}, 
        'SonyA7S2_20000': {'Kmax': 19.126, 'lam': -0.060213074, 'sigGs': 22.084776, 'sigGssig': 0.21820943, 'sigTL': 11.002351, 'sigTLsig': 0.28806436, 'sigR': 1.8810822, 'sigRsig': 0.18937257, 'bias': 0, 'biassig': 0.4984733, 'q': 6.103515625e-05, 'wp': 16383, 'bl': 512}, 
        'SonyA7S2_25600': {'Kmax': 24.48128, 'lam': -0.09089118, 'sigGs': 25.853043, 'sigGssig': 0.35371417, 'sigTL': 12.175712, 'sigTLsig': 0.4215717, 'sigR': 2.2760193, 'sigRsig': 0.2609267, 'bias': 0, 'biassig': 0.37568903, 'q': 6.103515625e-05, 'wp': 16383, 'bl': 512}
        }
```
我在复现时是使用的上面两个参数的Kmin和Kmax进行随机采样加噪，这点是否会影响实验结果呢？

**Comment by fenghansen** [comment]
我之前一直在忙没重跑，也没想到是哪里的问题，刚刚好像忽然猜到是啥问题了……
ELD在SonyA7S2上有TPAMI版的bias（black level error），在CVPR版没写，我这里面的对应CVPR的版本。那个权重参数我好像没放到这版代码里。你的出图是不是偏色很严重？如果是的话应该就是这个问题，按理说就这个问题对指标影响最大。
