### ISSUE TITLE
关于多帧融合

### ISSUE THREAD

**Issue by xxxxxxxxDSDNet** [megvii-research/PMN#11]
您好，非常感谢您分享代码。

请问是否会分享数据处理的code？比如多帧融合的过程。

**Comment by fenghansen** [comment]
merge_GT.py就是。对齐的部分用的内部实现的HDR+，没法开源，但```LRID_raw/npy/GT_aligns```里给对齐后的数据了，可以直接用，你也可以用```LRID_raw/100```下的原始数据自行对齐融合。```LRID_raw/GT```文件夹下有各种中间结果的可视化。

**Comment by xxxxxxxxDSDNet** [comment]
感谢您的回复和工作！
