### ISSUE TITLE
Exp是代表什么意思呢？ 

### ISSUE THREAD

**Issue by quhaoooo** [megvii-research/PMN#15]
大佬您好，我看到在LRID_RAW / bias 中的文件命名为 xxx_exp_xxxx, 其中的exp以及后面带的数字是什么意思呢？ 
比如说这个 002459_exp-16000000_iso-6400_2022_11_02_17_53_09_167_177554445439221_orientation_0_camera-0.dng， 那exp-16000000代表的含义是？

**Comment by fenghansen** [comment]
曝光时间，1,000,000是1ms
