### ISSUE TITLE
args['bl']和BLE之间的关系

### ISSUE THREAD

**Issue by quhaoooo** [megvii-research/PMN#16]
大佬，您好。 请问yaml里的args['bl']和darkshading中的BLE是什么关系呢？

**Comment by fenghansen** [comment]
args['bl']是从raw文件直接读出的metadata（black level），实际上各通道可能和metadata文件记载的不一样，所以单写了BLE（black level上的误差）。两者指向的是同一个变量（black level），一定程度上有混用，建议你根据实际需要检查一下。
