### ISSUE TITLE
关于在自定义数据上的测试

### ISSUE THREAD

**Issue by newaccountfor** [megvii-research/PMN#17]
大佬您好，如果我想在一个自定义数据集上进行去噪效果的验证的话，应该怎样写会比较好...

**Comment by fenghansen** [comment]
重写一个Dataset类（```data_process/real_datasets.py```），然后微调一下trainer_xxx.py。有配套数据要训练的话设定好配套的yaml文件（实验设置），然后调用train函数训练，有验证集的话基于eval函数适配一下，只有噪图的话就基于predict函数改。总有一款适合你。
总原则就是改供数据的方案和可视化方案就好，其他的真不用改啥。
