### ISSUE TITLE
about "Physics-guided Noise Neural Proxy for Low-light Raw Image Denoising"

### ISSUE THREAD

**Issue by ffmm123** [megvii-research/PMN#18]
hi, i read your this paper, and  i have some questions I'd like to ask you. the PPM model last layer about g(iso) is equivalent to estimated parameter k which as same as in the formula possion(x/k) *k ？The output of the model is directly multiplied by this k？

**Comment by fenghansen** [comment]
``g(iso)`` is ok to be the same as the system gain ``k``. 
We have made some changes to ``g(iso)`` in the submitted version. The submitted version is greatly improved compared to the arxiv version. Please refer to the official version in the future (it is not accessible yet).

**Comment by ffmm123** [comment]
hi， what‘s the "mfm" in process.py？ It represents the average number of raw images ?

**Comment by fenghansen** [comment]
yes (details have been discussed in the email)
