### ISSUE TITLE
about FPNk

### ISSUE THREAD

**Issue by TheZJZ** [megvii-research/PMN#19]
May I ask how the graphs of FPNk in the paper were generated? I noticed that in the provided xxk.npy files in the resources, there are only a few scattered points showing significant differences, unlike the pronounced variations in the corners as depicted in the paper.

**Comment by fenghansen** [comment]
We converted the color space and limited the value range for viewing.
https://github.com/megvii-research/PMN/blob/TPAMI/noise_estimation.py#L409C1-L416C92 
``` python
    plt.figure(figsize=(16,10))
    plt.imshow(ds_k.clip(-3*ds_k.std(),3*ds_k.std()))
    plt.colorbar()
    plt.savefig(f'{args["dst_dir"]}/darkshading{hint}{hint_dn}_k.png', bbox_inches='tight')
    plt.figure(figsize=(16,10))
    plt.imshow(ds_b.clip(-3*ds_b.std(),3*ds_b.std()))
    plt.colorbar()
    plt.savefig(f'{args["dst_dir"]}/darkshading{hint}{hint_dn}_b.png', bbox_inches='tight')
```
