### ISSUE TITLE
About IlluminanceCorrect

### ISSUE THREAD

**Issue by YangGangZhiQi** [megvii-research/PMN#2]
Hi， thanks for this great work. I  have a question about IlluminaceCorrect.correct() function.
![illuminance_correct](https://user-images.githubusercontent.com/87355944/184316378-d8af6938-8700-4fbe-9d20-00bf588066ec.png)
I could not understand the line 36~39, why these equations could complete illuminance correction? Is there some theory to support these equations? I would appreciate it if someone could help me?

**Comment by fenghansen** [comment]
This code is to make the sum of the signal values of pred (predict) and the sum of the signal values of source (GT) the same to achieve illuminance correction.
For the design details of `IlluminanceCorrect`, please refer to the [issue#19 of ELD](https://github.com/Vandermode/ELD/issues/19)

**Comment by YangGangZhiQi** [comment]
Thanks for you answer!
