### ISSUE TITLE
Invaid training command

### ISSUE THREAD

**Issue by xiaobiaodu** [megvii-research/PMN#4]
Hi

I use your training command.
`python3 trainer_SID.py -f runfiles/Ours.yml --mode train`

But it did not train but directly test.

**Comment by fenghansen** [comment]
I have changed the default logic for train/test, you can try again.
Now the terminal command is the highest priority and the yaml file is the second priority. 
I'm sorry I didn't notice this issue before (the yaml file was set to 'train' during test training).
