### ISSUE TITLE
关于训练数据

### ISSUE THREAD

**Issue by xiaobiaodu** [megvii-research/PMN#7]
您好！我看了下您的代码，发现训练数据的时候是用长曝光数据 除以一个倍数来合成noise数据作为输入，SID ELD中有短曝光数据，为什么不直接用短曝光数据合成呢？

**Comment by fenghansen** [comment]
同学你用中文问我就好回答了呀（笑
我觉得你可能对我们的代码和工作有些许误解：
1. 我没有“用长曝光数据 除以一个倍数来合成noise数据作为输入”，这是ELD的做法。
2. “SID ELD中有短曝光数据，为什么不直接用短曝光数据合成” 这句话我没太理解是怎么操作的，听起来像是配对数据训练？
3. 我们的实际做法是：仅用干净的长曝光数据合成信号相关的噪声（shot noise），然后叠加到本就包含真实噪声的配对的短曝光数据上，用于训练。这样就能在不破坏噪声分布的情况下增广数据。这就是SNA。

另外我记得你之前还在#5问过PSNR和SSIM的问题。我之前跑了一下好像没问题？进入那段代码前我已经把算好的raw_psnr和raw_ssim作为参数res传进去了啊？如果数值比论文里少10dB左右对不上那可能是传错版本了，不过我测的时候似乎是对的。

**Comment by xiaobiaodu** [comment]
请教下，你们计算PSNR SSIM时，是不是把网络输出 先clamp到 0与1 之间，然后 再乘以 255 计算PSNR跟SSIM呢

**Comment by fenghansen** [comment]
我自己比较习惯在GPU上算PSNR，就是代码里的PSNR_loss。那个是没乘255的，调一下常数就行，由于没有量化，所以可能会在小数点后3/4位比用图片算高一点点。
本文的代码是对齐ELD的，就是缩放到255再用quality_assess算。只要算PSNR时信号值域上限(1.0 or 255)没设置错，是否缩放数值范围没区别。
