### ISSUE TITLE
请问能否分享dark frames

### ISSUE THREAD

**Issue by wyf0912** [megvii-research/PMN#8]
首先非常感谢分享代码~！

请问能否分享下使用的dark frames？

**Comment by fenghansen** [comment]
这个数据要上传麻烦事很多，请你邮件说明单位和用途，我们讨论一下具体情况再说吧。

**Comment by wyf0912** [comment]
谢谢回复！ 我刚刚发到您学校邮箱了~
刚刚忘记说明，是纯科研使用
